# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-18 00:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221018_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventtype',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='script')]),
        ),
    ]
