# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-25 03:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221018_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$')])),
                ('size', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='^Tiny|Small|Medium|Large$')])),
                ('friendliness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('trainability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sheddingammount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('exerciseneeds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('gender', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$')])),
                ('color', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$')])),
                ('favoritefood', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9 ]+$')])),
                ('favoritetoy', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9 ]+$')])),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Breed')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='eventtype',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
